/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuthenticationEvent {
  'status' : string,
  'epiqId' : [] | [string],
  'failureReason' : [] | [string],
  'authMethod' : string,
  'ipContext' : [] | [string],
  'timestamp' : Time,
  'principalId' : Principal,
}
export type Chain = { 'btc' : null } |
  { 'evm' : null } |
  { 'icp' : null } |
  { 'custom' : null };
export interface CourseModule {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'steps' : Array<string>,
  'category' : string,
}
export interface CourseModuleContent {
  'doStep' : [] | [Array<QuizQuestion>],
  'show' : [] | [string],
  'tell' : string,
}
export interface CourseModuleWithQuestions {
  'id' : bigint,
  'title' : string,
  'content' : CourseModuleContent,
  'description' : string,
  'questions' : Array<QuizQuestion>,
}
export interface CourseProgress {
  'moduleId' : bigint,
  'user' : Principal,
  'completed' : boolean,
  'completedSteps' : Array<bigint>,
}
export interface CourseWithModules {
  'id' : bigint,
  'reward' : bigint,
  'title' : string,
  'availableToAll' : boolean,
  'description' : string,
  'assignedMemberTypes' : Array<MemberType>,
  'category' : string,
  'modules' : Array<CourseModuleWithQuestions>,
}
export interface DisplayNameChangeHistory {
  'timestamp' : Time,
  'principalId' : Principal,
  'newName' : string,
  'oldName' : string,
}
export interface EpiqWallet {
  'publicAddress' : string,
  'metadata' : [] | [string],
  'chain' : Chain,
  'createdAt' : Time,
  'privateKey' : [] | [string],
  'recoveryPhrase' : [] | [string],
  'walletLabel' : [] | [string],
  'walletId' : bigint,
}
export interface EpqReward {
  'id' : bigint,
  'verified' : boolean,
  'source' : string,
  'user' : Principal,
  'timestamp' : Time,
  'amount' : bigint,
}
export interface FirebaseAuthResponse {
  'epiqId' : [] | [string],
  'displayName' : [] | [string],
  'sessionExpiresAt' : [] | [Time],
  'walletAddress' : [] | [string],
  'email' : [] | [string],
  'message' : string,
  'memberType' : [] | [string],
  'success' : boolean,
  'principalId' : [] | [Principal],
}
export type MemberType = { 'member' : null } |
  { 'trustee' : null } |
  { 'admin' : null } |
  { 'citizen' : null } |
  { 'beneficiary' : null } |
  { 'superAdmin' : null } |
  { 'business' : null } |
  { 'ambassador' : null } |
  { 'partner' : null };
export interface Message {
  'id' : bigint,
  'to' : Principal,
  'content' : string,
  'from' : Principal,
  'read' : boolean,
  'timestamp' : Time,
}
export interface Quest {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'steps' : Array<string>,
  'category' : string,
}
export interface QuestModule {
  'id' : bigint,
  'reward' : bigint,
  'title' : string,
  'description' : string,
  'steps' : Array<QuestStep>,
  'category' : string,
}
export interface QuestProgress {
  'user' : Principal,
  'completed' : boolean,
  'questId' : bigint,
  'completedSteps' : Array<bigint>,
}
export interface QuestProgressRecord {
  'moduleId' : bigint,
  'user' : Principal,
  'completed' : boolean,
  'completedSteps' : Array<bigint>,
  'timestamp' : Time,
}
export interface QuestStep {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'stepType' : string,
  'quizQuestions' : [] | [Array<QuizQuestion>],
  'videoUrl' : [] | [string],
}
export interface QuizQuestion {
  'question' : string,
  'correctAnswer' : bigint,
  'options' : Array<string>,
}
export type Time = bigint;
export interface Transaction {
  'id' : bigint,
  'to' : Principal,
  'status' : string,
  'from' : Principal,
  'currency' : string,
  'timestamp' : Time,
  'amount' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'icpWalletAddress' : string,
  'displayName' : string,
  'name' : string,
  'email' : string,
  'importedFromFirebase' : boolean,
  'memberType' : string,
  'btcWalletAddress' : string,
  'ethWalletAddress' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'authenticateWithFirebase' : ActorMethod<
    [string, string],
    FirebaseAuthResponse
  >,
  'cleanupExpiredSessions' : ActorMethod<[], bigint>,
  'createCourse' : ActorMethod<
    [string, string, string, [] | [Array<CourseModuleWithQuestions>]],
    bigint
  >,
  'createCourseWithModules' : ActorMethod<
    [
      string,
      string,
      string,
      Array<CourseModuleWithQuestions>,
      bigint,
      boolean,
      Array<MemberType>,
    ],
    bigint
  >,
  'createQuest' : ActorMethod<[string, string, string, Array<string>], bigint>,
  'createTransaction' : ActorMethod<[Principal, bigint, string], bigint>,
  'createWallet' : ActorMethod<
    [[] | [string]],
    {
      'chain' : Chain,
      'privateKey' : [] | [string],
      'address' : string,
      'recoveryPhrase' : [] | [string],
      'walletId' : bigint,
    }
  >,
  'findUserByDisplayName' : ActorMethod<[string], Principal>,
  'getAllCourseModules' : ActorMethod<[], Array<CourseModule>>,
  'getAllCourses' : ActorMethod<[], Array<CourseWithModules>>,
  'getAllMessages' : ActorMethod<[], Array<Message>>,
  'getAllQuestModules' : ActorMethod<[], Array<QuestModule>>,
  'getAllQuests' : ActorMethod<[], Array<Quest>>,
  'getAllUserCourseProgress' : ActorMethod<
    [],
    Array<[Principal, Array<CourseProgress>]>
  >,
  'getAllUserProfiles' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getAllUserQuestProgress' : ActorMethod<
    [],
    Array<[Principal, Array<QuestProgress>]>
  >,
  'getAllUserQuestProgressRecords' : ActorMethod<
    [],
    Array<[Principal, Array<QuestProgressRecord>]>
  >,
  'getAuthenticationAuditLog' : ActorMethod<[], Array<AuthenticationEvent>>,
  'getAuthenticationAuditLogByEpiqId' : ActorMethod<
    [string],
    Array<AuthenticationEvent>
  >,
  'getAuthenticationAuditLogByMethod' : ActorMethod<
    [string],
    Array<AuthenticationEvent>
  >,
  'getAuthenticationAuditLogByPrincipal' : ActorMethod<
    [Principal],
    Array<AuthenticationEvent>
  >,
  'getAuthenticationAuditLogByStatus' : ActorMethod<
    [string],
    Array<AuthenticationEvent>
  >,
  'getBtcBalance' : ActorMethod<[string], string>,
  'getBtcTransactionHistory' : ActorMethod<[string], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDisplayNameChangeHistory' : ActorMethod<
    [],
    Array<DisplayNameChangeHistory>
  >,
  'getDisplayNameChangeHistoryByDisplayName' : ActorMethod<
    [string],
    Array<DisplayNameChangeHistory>
  >,
  'getDisplayNameChangeHistoryByPrincipal' : ActorMethod<
    [Principal],
    Array<DisplayNameChangeHistory>
  >,
  'getEpiqIdByPrincipal' : ActorMethod<[Principal], string>,
  'getEthBalance' : ActorMethod<[string], string>,
  'getEthTransactionHistory' : ActorMethod<[string], string>,
  'getIcpBalance' : ActorMethod<[string], string>,
  'getIcpTransactionHistory' : ActorMethod<[string], string>,
  'getMessagesWithUser' : ActorMethod<[Principal], Array<Message>>,
  'getPrincipalByEpiqId' : ActorMethod<[string], Principal>,
  'getTransaction' : ActorMethod<[bigint], [] | [Transaction]>,
  'getUserCourseProgress' : ActorMethod<[Principal], Array<CourseProgress>>,
  'getUserEpqRewards' : ActorMethod<[Principal], Array<EpqReward>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserQuestProgress' : ActorMethod<[Principal], Array<QuestProgress>>,
  'getUserQuestProgressRecords' : ActorMethod<
    [Principal],
    Array<QuestProgressRecord>
  >,
  'getUserTransactions' : ActorMethod<[], Array<Transaction>>,
  'getWallet' : ActorMethod<[bigint], EpiqWallet>,
  'hasValidFirebaseSession' : ActorMethod<[], boolean>,
  'importSingleFirebaseUser' : ActorMethod<[string], string>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listWallets' : ActorMethod<[], Array<EpiqWallet>>,
  'logoutFirebaseSession' : ActorMethod<[], undefined>,
  'lookupPrincipalByEpiqId' : ActorMethod<[string], [] | [Principal]>,
  'mapEpiqIdToPrincipal' : ActorMethod<[string, Principal], undefined>,
  'markMessageAsRead' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], bigint>,
  'syncFirebaseUserData' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCourseProgress' : ActorMethod<
    [bigint, Array<bigint>, boolean],
    undefined
  >,
  'updateQuestProgress' : ActorMethod<
    [bigint, Array<bigint>, boolean],
    undefined
  >,
  'updateQuestProgressRecord' : ActorMethod<
    [bigint, Array<bigint>, boolean],
    undefined
  >,
  'updateUserMemberType' : ActorMethod<[Principal, string], undefined>,
  'updateWalletLabel' : ActorMethod<[bigint, [] | [string]], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];