/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const FirebaseAuthResponse = IDL.Record({
  'epiqId' : IDL.Opt(IDL.Text),
  'displayName' : IDL.Opt(IDL.Text),
  'sessionExpiresAt' : IDL.Opt(Time),
  'walletAddress' : IDL.Opt(IDL.Text),
  'email' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'memberType' : IDL.Opt(IDL.Text),
  'success' : IDL.Bool,
  'principalId' : IDL.Opt(IDL.Principal),
});
export const QuizQuestion = IDL.Record({
  'question' : IDL.Text,
  'correctAnswer' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const CourseModuleContent = IDL.Record({
  'doStep' : IDL.Opt(IDL.Vec(QuizQuestion)),
  'show' : IDL.Opt(IDL.Text),
  'tell' : IDL.Text,
});
export const CourseModuleWithQuestions = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : CourseModuleContent,
  'description' : IDL.Text,
  'questions' : IDL.Vec(QuizQuestion),
});
export const MemberType = IDL.Variant({
  'member' : IDL.Null,
  'trustee' : IDL.Null,
  'admin' : IDL.Null,
  'citizen' : IDL.Null,
  'beneficiary' : IDL.Null,
  'superAdmin' : IDL.Null,
  'business' : IDL.Null,
  'ambassador' : IDL.Null,
  'partner' : IDL.Null,
});
export const CourseModule = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'steps' : IDL.Vec(IDL.Text),
  'category' : IDL.Text,
});
export const CourseWithModules = IDL.Record({
  'id' : IDL.Nat,
  'reward' : IDL.Nat,
  'title' : IDL.Text,
  'availableToAll' : IDL.Bool,
  'description' : IDL.Text,
  'assignedMemberTypes' : IDL.Vec(MemberType),
  'category' : IDL.Text,
  'modules' : IDL.Vec(CourseModuleWithQuestions),
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'to' : IDL.Principal,
  'content' : IDL.Text,
  'from' : IDL.Principal,
  'read' : IDL.Bool,
  'timestamp' : Time,
});
export const QuestStep = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'stepType' : IDL.Text,
  'quizQuestions' : IDL.Opt(IDL.Vec(QuizQuestion)),
  'videoUrl' : IDL.Opt(IDL.Text),
});
export const QuestModule = IDL.Record({
  'id' : IDL.Nat,
  'reward' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'steps' : IDL.Vec(QuestStep),
  'category' : IDL.Text,
});
export const Quest = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'steps' : IDL.Vec(IDL.Text),
  'category' : IDL.Text,
});
export const CourseProgress = IDL.Record({
  'moduleId' : IDL.Nat,
  'user' : IDL.Principal,
  'completed' : IDL.Bool,
  'completedSteps' : IDL.Vec(IDL.Nat),
});
export const UserProfile = IDL.Record({
  'icpWalletAddress' : IDL.Text,
  'displayName' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'importedFromFirebase' : IDL.Bool,
  'memberType' : IDL.Text,
  'btcWalletAddress' : IDL.Text,
  'ethWalletAddress' : IDL.Text,
});
export const QuestProgress = IDL.Record({
  'user' : IDL.Principal,
  'completed' : IDL.Bool,
  'questId' : IDL.Nat,
  'completedSteps' : IDL.Vec(IDL.Nat),
});
export const QuestProgressRecord = IDL.Record({
  'moduleId' : IDL.Nat,
  'user' : IDL.Principal,
  'completed' : IDL.Bool,
  'completedSteps' : IDL.Vec(IDL.Nat),
  'timestamp' : Time,
});
export const AuthenticationEvent = IDL.Record({
  'status' : IDL.Text,
  'epiqId' : IDL.Opt(IDL.Text),
  'failureReason' : IDL.Opt(IDL.Text),
  'authMethod' : IDL.Text,
  'ipContext' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'principalId' : IDL.Principal,
});
export const DisplayNameChangeHistory = IDL.Record({
  'timestamp' : Time,
  'principalId' : IDL.Principal,
  'newName' : IDL.Text,
  'oldName' : IDL.Text,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'to' : IDL.Principal,
  'status' : IDL.Text,
  'from' : IDL.Principal,
  'currency' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});
export const EpqReward = IDL.Record({
  'id' : IDL.Nat,
  'verified' : IDL.Bool,
  'source' : IDL.Text,
  'user' : IDL.Principal,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});
export const EpiqWallet = IDL.Record({
  'publicAddress' : IDL.Text,
  'metadata' : IDL.Opt(IDL.Text),
  'createdAt' : Time,
  'walletLabel' : IDL.Opt(IDL.Text),
  'walletId' : IDL.Nat,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'authenticateWithFirebase' : IDL.Func(
      [IDL.Text, IDL.Text],
      [FirebaseAuthResponse],
      [],
    ),
  'cleanupExpiredSessions' : IDL.Func([], [IDL.Nat], []),
  'createCourse' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Vec(CourseModuleWithQuestions)),
      ],
      [IDL.Nat],
      [],
    ),
  'createCourseWithModules' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(CourseModuleWithQuestions),
        IDL.Nat,
        IDL.Bool,
        IDL.Vec(MemberType),
      ],
      [IDL.Nat],
      [],
    ),
  'createQuest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'createTransaction' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createWallet' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Text], []),
  'findUserByDisplayName' : IDL.Func([IDL.Text], [IDL.Principal], ['query']),
  'getAllCourseModules' : IDL.Func([], [IDL.Vec(CourseModule)], ['query']),
  'getAllCourses' : IDL.Func([], [IDL.Vec(CourseWithModules)], ['query']),
  'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getAllQuestModules' : IDL.Func([], [IDL.Vec(QuestModule)], ['query']),
  'getAllQuests' : IDL.Func([], [IDL.Vec(Quest)], ['query']),
  'getAllUserCourseProgress' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(CourseProgress)))],
      ['query'],
    ),
  'getAllUserProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getAllUserQuestProgress' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(QuestProgress)))],
      ['query'],
    ),
  'getAllUserQuestProgressRecords' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(QuestProgressRecord)))],
      ['query'],
    ),
  'getAuthenticationAuditLog' : IDL.Func(
      [],
      [IDL.Vec(AuthenticationEvent)],
      ['query'],
    ),
  'getAuthenticationAuditLogByEpiqId' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AuthenticationEvent)],
      ['query'],
    ),
  'getAuthenticationAuditLogByMethod' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AuthenticationEvent)],
      ['query'],
    ),
  'getAuthenticationAuditLogByPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(AuthenticationEvent)],
      ['query'],
    ),
  'getAuthenticationAuditLogByStatus' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AuthenticationEvent)],
      ['query'],
    ),
  'getBtcBalance' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getBtcTransactionHistory' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDisplayNameChangeHistory' : IDL.Func(
      [],
      [IDL.Vec(DisplayNameChangeHistory)],
      ['query'],
    ),
  'getDisplayNameChangeHistoryByDisplayName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DisplayNameChangeHistory)],
      ['query'],
    ),
  'getDisplayNameChangeHistoryByPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(DisplayNameChangeHistory)],
      ['query'],
    ),
  'getEpiqIdByPrincipal' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
  'getEthBalance' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getEthTransactionHistory' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getIcpBalance' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getIcpTransactionHistory' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getMessagesWithUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getPrincipalByEpiqId' : IDL.Func([IDL.Text], [IDL.Principal], ['query']),
  'getTransaction' : IDL.Func([IDL.Nat], [IDL.Opt(Transaction)], ['query']),
  'getUserCourseProgress' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(CourseProgress)],
      ['query'],
    ),
  'getUserEpqRewards' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(EpqReward)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserQuestProgress' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(QuestProgress)],
      ['query'],
    ),
  'getUserQuestProgressRecords' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(QuestProgressRecord)],
      ['query'],
    ),
  'getUserTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getWallet' : IDL.Func([IDL.Nat], [EpiqWallet], ['query']),
  'hasValidFirebaseSession' : IDL.Func([], [IDL.Bool], ['query']),
  'importSingleFirebaseUser' : IDL.Func([IDL.Text], [IDL.Text], []),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listWallets' : IDL.Func([], [IDL.Vec(EpiqWallet)], ['query']),
  'logoutFirebaseSession' : IDL.Func([], [], []),
  'lookupPrincipalByEpiqId' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Principal)],
      ['query'],
    ),
  'mapEpiqIdToPrincipal' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'markMessageAsRead' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
  'syncFirebaseUserData' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCourseProgress' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Nat), IDL.Bool],
      [],
      [],
    ),
  'updateQuestProgress' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Nat), IDL.Bool],
      [],
      [],
    ),
  'updateQuestProgressRecord' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Nat), IDL.Bool],
      [],
      [],
    ),
  'updateUserMemberType' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'updateWalletLabel' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const FirebaseAuthResponse = IDL.Record({
    'epiqId' : IDL.Opt(IDL.Text),
    'displayName' : IDL.Opt(IDL.Text),
    'sessionExpiresAt' : IDL.Opt(Time),
    'walletAddress' : IDL.Opt(IDL.Text),
    'email' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'memberType' : IDL.Opt(IDL.Text),
    'success' : IDL.Bool,
    'principalId' : IDL.Opt(IDL.Principal),
  });
  const QuizQuestion = IDL.Record({
    'question' : IDL.Text,
    'correctAnswer' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const CourseModuleContent = IDL.Record({
    'doStep' : IDL.Opt(IDL.Vec(QuizQuestion)),
    'show' : IDL.Opt(IDL.Text),
    'tell' : IDL.Text,
  });
  const CourseModuleWithQuestions = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : CourseModuleContent,
    'description' : IDL.Text,
    'questions' : IDL.Vec(QuizQuestion),
  });
  const MemberType = IDL.Variant({
    'member' : IDL.Null,
    'trustee' : IDL.Null,
    'admin' : IDL.Null,
    'citizen' : IDL.Null,
    'beneficiary' : IDL.Null,
    'superAdmin' : IDL.Null,
    'business' : IDL.Null,
    'ambassador' : IDL.Null,
    'partner' : IDL.Null,
  });
  const CourseModule = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'steps' : IDL.Vec(IDL.Text),
    'category' : IDL.Text,
  });
  const CourseWithModules = IDL.Record({
    'id' : IDL.Nat,
    'reward' : IDL.Nat,
    'title' : IDL.Text,
    'availableToAll' : IDL.Bool,
    'description' : IDL.Text,
    'assignedMemberTypes' : IDL.Vec(MemberType),
    'category' : IDL.Text,
    'modules' : IDL.Vec(CourseModuleWithQuestions),
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'to' : IDL.Principal,
    'content' : IDL.Text,
    'from' : IDL.Principal,
    'read' : IDL.Bool,
    'timestamp' : Time,
  });
  const QuestStep = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'stepType' : IDL.Text,
    'quizQuestions' : IDL.Opt(IDL.Vec(QuizQuestion)),
    'videoUrl' : IDL.Opt(IDL.Text),
  });
  const QuestModule = IDL.Record({
    'id' : IDL.Nat,
    'reward' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'steps' : IDL.Vec(QuestStep),
    'category' : IDL.Text,
  });
  const Quest = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'steps' : IDL.Vec(IDL.Text),
    'category' : IDL.Text,
  });
  const CourseProgress = IDL.Record({
    'moduleId' : IDL.Nat,
    'user' : IDL.Principal,
    'completed' : IDL.Bool,
    'completedSteps' : IDL.Vec(IDL.Nat),
  });
  const UserProfile = IDL.Record({
    'icpWalletAddress' : IDL.Text,
    'displayName' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'importedFromFirebase' : IDL.Bool,
    'memberType' : IDL.Text,
    'btcWalletAddress' : IDL.Text,
    'ethWalletAddress' : IDL.Text,
  });
  const QuestProgress = IDL.Record({
    'user' : IDL.Principal,
    'completed' : IDL.Bool,
    'questId' : IDL.Nat,
    'completedSteps' : IDL.Vec(IDL.Nat),
  });
  const QuestProgressRecord = IDL.Record({
    'moduleId' : IDL.Nat,
    'user' : IDL.Principal,
    'completed' : IDL.Bool,
    'completedSteps' : IDL.Vec(IDL.Nat),
    'timestamp' : Time,
  });
  const AuthenticationEvent = IDL.Record({
    'status' : IDL.Text,
    'epiqId' : IDL.Opt(IDL.Text),
    'failureReason' : IDL.Opt(IDL.Text),
    'authMethod' : IDL.Text,
    'ipContext' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'principalId' : IDL.Principal,
  });
  const DisplayNameChangeHistory = IDL.Record({
    'timestamp' : Time,
    'principalId' : IDL.Principal,
    'newName' : IDL.Text,
    'oldName' : IDL.Text,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'to' : IDL.Principal,
    'status' : IDL.Text,
    'from' : IDL.Principal,
    'currency' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  const EpqReward = IDL.Record({
    'id' : IDL.Nat,
    'verified' : IDL.Bool,
    'source' : IDL.Text,
    'user' : IDL.Principal,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  const EpiqWallet = IDL.Record({
    'publicAddress' : IDL.Text,
    'metadata' : IDL.Opt(IDL.Text),
    'createdAt' : Time,
    'walletLabel' : IDL.Opt(IDL.Text),
    'walletId' : IDL.Nat,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'authenticateWithFirebase' : IDL.Func(
        [IDL.Text, IDL.Text],
        [FirebaseAuthResponse],
        [],
      ),
    'cleanupExpiredSessions' : IDL.Func([], [IDL.Nat], []),
    'createCourse' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Vec(CourseModuleWithQuestions)),
        ],
        [IDL.Nat],
        [],
      ),
    'createCourseWithModules' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(CourseModuleWithQuestions),
          IDL.Nat,
          IDL.Bool,
          IDL.Vec(MemberType),
        ],
        [IDL.Nat],
        [],
      ),
    'createQuest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'createTransaction' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createWallet' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Text], []),
    'findUserByDisplayName' : IDL.Func([IDL.Text], [IDL.Principal], ['query']),
    'getAllCourseModules' : IDL.Func([], [IDL.Vec(CourseModule)], ['query']),
    'getAllCourses' : IDL.Func([], [IDL.Vec(CourseWithModules)], ['query']),
    'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getAllQuestModules' : IDL.Func([], [IDL.Vec(QuestModule)], ['query']),
    'getAllQuests' : IDL.Func([], [IDL.Vec(Quest)], ['query']),
    'getAllUserCourseProgress' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(CourseProgress)))],
        ['query'],
      ),
    'getAllUserProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getAllUserQuestProgress' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(QuestProgress)))],
        ['query'],
      ),
    'getAllUserQuestProgressRecords' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(QuestProgressRecord)))],
        ['query'],
      ),
    'getAuthenticationAuditLog' : IDL.Func(
        [],
        [IDL.Vec(AuthenticationEvent)],
        ['query'],
      ),
    'getAuthenticationAuditLogByEpiqId' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AuthenticationEvent)],
        ['query'],
      ),
    'getAuthenticationAuditLogByMethod' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AuthenticationEvent)],
        ['query'],
      ),
    'getAuthenticationAuditLogByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(AuthenticationEvent)],
        ['query'],
      ),
    'getAuthenticationAuditLogByStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AuthenticationEvent)],
        ['query'],
      ),
    'getBtcBalance' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getBtcTransactionHistory' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDisplayNameChangeHistory' : IDL.Func(
        [],
        [IDL.Vec(DisplayNameChangeHistory)],
        ['query'],
      ),
    'getDisplayNameChangeHistoryByDisplayName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DisplayNameChangeHistory)],
        ['query'],
      ),
    'getDisplayNameChangeHistoryByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(DisplayNameChangeHistory)],
        ['query'],
      ),
    'getEpiqIdByPrincipal' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
    'getEthBalance' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getEthTransactionHistory' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getIcpBalance' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getIcpTransactionHistory' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getMessagesWithUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getPrincipalByEpiqId' : IDL.Func([IDL.Text], [IDL.Principal], ['query']),
    'getTransaction' : IDL.Func([IDL.Nat], [IDL.Opt(Transaction)], ['query']),
    'getUserCourseProgress' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(CourseProgress)],
        ['query'],
      ),
    'getUserEpqRewards' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(EpqReward)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserQuestProgress' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(QuestProgress)],
        ['query'],
      ),
    'getUserQuestProgressRecords' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(QuestProgressRecord)],
        ['query'],
      ),
    'getUserTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getWallet' : IDL.Func([IDL.Nat], [EpiqWallet], ['query']),
    'hasValidFirebaseSession' : IDL.Func([], [IDL.Bool], ['query']),
    'importSingleFirebaseUser' : IDL.Func([IDL.Text], [IDL.Text], []),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listWallets' : IDL.Func([], [IDL.Vec(EpiqWallet)], ['query']),
    'logoutFirebaseSession' : IDL.Func([], [], []),
    'lookupPrincipalByEpiqId' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Principal)],
        ['query'],
      ),
    'mapEpiqIdToPrincipal' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'markMessageAsRead' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
    'syncFirebaseUserData' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCourseProgress' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Nat), IDL.Bool],
        [],
        [],
      ),
    'updateQuestProgress' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Nat), IDL.Bool],
        [],
        [],
      ),
    'updateQuestProgressRecord' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Nat), IDL.Bool],
        [],
        [],
      ),
    'updateUserMemberType' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'updateWalletLabel' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };