/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface QuestProgress {
    user: Principal;
    completed: boolean;
    questId: bigint;
    completedSteps: Array<bigint>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface QuizQuestion {
    question: string;
    correctAnswer: bigint;
    options: Array<string>;
}
export interface CourseModuleContent {
    doStep?: Array<QuizQuestion>;
    show?: string;
    tell: string;
}
export interface CourseWithModules {
    id: bigint;
    reward: bigint;
    title: string;
    availableToAll: boolean;
    description: string;
    assignedMemberTypes: Array<MemberType>;
    category: string;
    modules: Array<CourseModuleWithQuestions>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Transaction {
    id: bigint;
    to: Principal;
    status: string;
    from: Principal;
    currency: string;
    timestamp: Time;
    amount: bigint;
}
export interface CourseModule {
    id: bigint;
    title: string;
    description: string;
    steps: Array<string>;
    category: string;
}
export interface QuestStep {
    id: bigint;
    title: string;
    content: string;
    stepType: string;
    quizQuestions?: Array<QuizQuestion>;
    videoUrl?: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface FirebaseAuthResponse {
    epiqId?: string;
    displayName?: string;
    sessionExpiresAt?: Time;
    walletAddress?: string;
    email?: string;
    message: string;
    memberType?: string;
    success: boolean;
    principalId?: Principal;
}
export interface EpiqWallet {
    publicAddress: string;
    metadata?: string;
    chain: Chain;
    createdAt: Time;
    privateKey?: string;
    recoveryPhrase?: string;
    walletLabel?: string;
    walletId: bigint;
}
export interface AuthenticationEvent {
    status: string;
    epiqId?: string;
    failureReason?: string;
    authMethod: string;
    ipContext?: string;
    timestamp: Time;
    principalId: Principal;
}
export interface EpqReward {
    id: bigint;
    verified: boolean;
    source: string;
    user: Principal;
    timestamp: Time;
    amount: bigint;
}
export interface QuestModule {
    id: bigint;
    reward: bigint;
    title: string;
    description: string;
    steps: Array<QuestStep>;
    category: string;
}
export interface QuestProgressRecord {
    moduleId: bigint;
    user: Principal;
    completed: boolean;
    completedSteps: Array<bigint>;
    timestamp: Time;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface CourseModuleWithQuestions {
    id: bigint;
    title: string;
    content: CourseModuleContent;
    description: string;
    questions: Array<QuizQuestion>;
}
export interface Quest {
    id: bigint;
    title: string;
    description: string;
    steps: Array<string>;
    category: string;
}
export interface Message {
    id: bigint;
    to: Principal;
    content: string;
    from: Principal;
    read: boolean;
    timestamp: Time;
}
export interface CourseProgress {
    moduleId: bigint;
    user: Principal;
    completed: boolean;
    completedSteps: Array<bigint>;
}
export interface DisplayNameChangeHistory {
    timestamp: Time;
    principalId: Principal;
    newName: string;
    oldName: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    icpWalletAddress: string;
    displayName: string;
    name: string;
    email: string;
    importedFromFirebase: boolean;
    memberType: string;
    btcWalletAddress: string;
    ethWalletAddress: string;
}
export enum Chain {
    btc = "btc",
    evm = "evm",
    icp = "icp",
    custom = "custom"
}
export enum MemberType {
    member = "member",
    trustee = "trustee",
    admin = "admin",
    citizen = "citizen",
    beneficiary = "beneficiary",
    superAdmin = "superAdmin",
    business = "business",
    ambassador = "ambassador",
    partner = "partner"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blob_hash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    authenticateWithFirebase(epiqId: string, password: string): Promise<FirebaseAuthResponse>;
    cleanupExpiredSessions(): Promise<bigint>;
    createCourse(title: string, description: string, category: string, initialModules: Array<CourseModuleWithQuestions> | null): Promise<bigint>;
    createCourseWithModules(title: string, description: string, category: string, modules: Array<CourseModuleWithQuestions>, reward: bigint, availableToAll: boolean, assignedMemberTypes: Array<MemberType>): Promise<bigint>;
    createQuest(title: string, description: string, category: string, steps: Array<string>): Promise<bigint>;
    createTransaction(to: Principal, amount: bigint, currency: string): Promise<bigint>;
    createWallet(walletLabel: string | null): Promise<{
        chain: Chain;
        privateKey?: string;
        address: string;
        recoveryPhrase?: string;
        walletId: bigint;
    }>;
    findUserByDisplayName(displayName: string): Promise<Principal>;
    getAllCourseModules(): Promise<Array<CourseModule>>;
    getAllCourses(): Promise<Array<CourseWithModules>>;
    getAllMessages(): Promise<Array<Message>>;
    getAllQuestModules(): Promise<Array<QuestModule>>;
    getAllQuests(): Promise<Array<Quest>>;
    getAllUserCourseProgress(): Promise<Array<[Principal, Array<CourseProgress>]>>;
    getAllUserProfiles(): Promise<Array<[Principal, UserProfile]>>;
    getAllUserQuestProgress(): Promise<Array<[Principal, Array<QuestProgress>]>>;
    getAllUserQuestProgressRecords(): Promise<Array<[Principal, Array<QuestProgressRecord>]>>;
    getAuthenticationAuditLog(): Promise<Array<AuthenticationEvent>>;
    getAuthenticationAuditLogByEpiqId(epiqId: string): Promise<Array<AuthenticationEvent>>;
    getAuthenticationAuditLogByMethod(authMethod: string): Promise<Array<AuthenticationEvent>>;
    getAuthenticationAuditLogByPrincipal(principalId: Principal): Promise<Array<AuthenticationEvent>>;
    getAuthenticationAuditLogByStatus(status: string): Promise<Array<AuthenticationEvent>>;
    getBtcBalance(address: string): Promise<string>;
    getBtcTransactionHistory(address: string): Promise<string>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDisplayNameChangeHistory(): Promise<Array<DisplayNameChangeHistory>>;
    getDisplayNameChangeHistoryByDisplayName(displayName: string): Promise<Array<DisplayNameChangeHistory>>;
    getDisplayNameChangeHistoryByPrincipal(principalId: Principal): Promise<Array<DisplayNameChangeHistory>>;
    getEpiqIdByPrincipal(principalId: Principal): Promise<string>;
    getEthBalance(address: string): Promise<string>;
    getEthTransactionHistory(address: string): Promise<string>;
    getIcpBalance(address: string): Promise<string>;
    getIcpTransactionHistory(address: string): Promise<string>;
    getMessagesWithUser(user: Principal): Promise<Array<Message>>;
    getPrincipalByEpiqId(epiqId: string): Promise<Principal>;
    getTransaction(id: bigint): Promise<Transaction | null>;
    getUserCourseProgress(user: Principal): Promise<Array<CourseProgress>>;
    getUserEpqRewards(user: Principal): Promise<Array<EpqReward>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserQuestProgress(user: Principal): Promise<Array<QuestProgress>>;
    getUserQuestProgressRecords(user: Principal): Promise<Array<QuestProgressRecord>>;
    getUserTransactions(): Promise<Array<Transaction>>;
    getWallet(walletId: bigint): Promise<EpiqWallet>;
    hasValidFirebaseSession(): Promise<boolean>;
    importSingleFirebaseUser(email: string): Promise<string>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    listWallets(): Promise<Array<EpiqWallet>>;
    logoutFirebaseSession(): Promise<void>;
    lookupPrincipalByEpiqId(epiqId: string): Promise<Principal | null>;
    mapEpiqIdToPrincipal(epiqId: string, principalId: Principal): Promise<void>;
    markMessageAsRead(messageId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendMessage(to: Principal, content: string): Promise<bigint>;
    syncFirebaseUserData(epiqId: string, displayName: string, email: string, walletAddress: string, memberType: string): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateCourseProgress(moduleId: bigint, completedSteps: Array<bigint>, completed: boolean): Promise<void>;
    updateQuestProgress(questId: bigint, completedSteps: Array<bigint>, completed: boolean): Promise<void>;
    updateQuestProgressRecord(moduleId: bigint, completedSteps: Array<bigint>, completed: boolean): Promise<void>;
    updateUserMemberType(user: Principal, memberType: string): Promise<void>;
    updateWalletLabel(walletId: bigint, newLabel: string | null): Promise<void>;
}
import type { AuthenticationEvent as _AuthenticationEvent, Chain as _Chain, CourseModuleContent as _CourseModuleContent, CourseModuleWithQuestions as _CourseModuleWithQuestions, CourseWithModules as _CourseWithModules, EpiqWallet as _EpiqWallet, FirebaseAuthResponse as _FirebaseAuthResponse, MemberType as _MemberType, QuestModule as _QuestModule, QuestStep as _QuestStep, QuizQuestion as _QuizQuestion, Time as _Time, Transaction as _Transaction, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async authenticateWithFirebase(arg0: string, arg1: string): Promise<FirebaseAuthResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.authenticateWithFirebase(arg0, arg1);
                return from_candid_FirebaseAuthResponse_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.authenticateWithFirebase(arg0, arg1);
            return from_candid_FirebaseAuthResponse_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async cleanupExpiredSessions(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.cleanupExpiredSessions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cleanupExpiredSessions();
            return result;
        }
    }
    async createCourse(arg0: string, arg1: string, arg2: string, arg3: Array<CourseModuleWithQuestions> | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCourse(arg0, arg1, arg2, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCourse(arg0, arg1, arg2, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async createCourseWithModules(arg0: string, arg1: string, arg2: string, arg3: Array<CourseModuleWithQuestions>, arg4: bigint, arg5: boolean, arg6: Array<MemberType>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCourseWithModules(arg0, arg1, arg2, to_candid_vec_n16(this._uploadFile, this._downloadFile, arg3), arg4, arg5, to_candid_vec_n21(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCourseWithModules(arg0, arg1, arg2, to_candid_vec_n16(this._uploadFile, this._downloadFile, arg3), arg4, arg5, to_candid_vec_n21(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async createQuest(arg0: string, arg1: string, arg2: string, arg3: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createQuest(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createQuest(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createTransaction(arg0: Principal, arg1: bigint, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTransaction(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTransaction(arg0, arg1, arg2);
            return result;
        }
    }
    async createWallet(arg0: string | null): Promise<{
        chain: Chain;
        privateKey?: string;
        address: string;
        recoveryPhrase?: string;
        walletId: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createWallet(to_candid_opt_n24(this._uploadFile, this._downloadFile, arg0));
                return from_candid_record_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWallet(to_candid_opt_n24(this._uploadFile, this._downloadFile, arg0));
            return from_candid_record_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async findUserByDisplayName(arg0: string): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.findUserByDisplayName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findUserByDisplayName(arg0);
            return result;
        }
    }
    async getAllCourseModules(): Promise<Array<CourseModule>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCourseModules();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCourseModules();
            return result;
        }
    }
    async getAllCourses(): Promise<Array<CourseWithModules>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCourses();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCourses();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMessages(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMessages();
            return result;
        }
    }
    async getAllQuestModules(): Promise<Array<QuestModule>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllQuestModules();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllQuestModules();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllQuests(): Promise<Array<Quest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllQuests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllQuests();
            return result;
        }
    }
    async getAllUserCourseProgress(): Promise<Array<[Principal, Array<CourseProgress>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserCourseProgress();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserCourseProgress();
            return result;
        }
    }
    async getAllUserProfiles(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return result;
        }
    }
    async getAllUserQuestProgress(): Promise<Array<[Principal, Array<QuestProgress>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserQuestProgress();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserQuestProgress();
            return result;
        }
    }
    async getAllUserQuestProgressRecords(): Promise<Array<[Principal, Array<QuestProgressRecord>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserQuestProgressRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserQuestProgressRecords();
            return result;
        }
    }
    async getAuthenticationAuditLog(): Promise<Array<AuthenticationEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuthenticationAuditLog();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuthenticationAuditLog();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAuthenticationAuditLogByEpiqId(arg0: string): Promise<Array<AuthenticationEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuthenticationAuditLogByEpiqId(arg0);
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuthenticationAuditLogByEpiqId(arg0);
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAuthenticationAuditLogByMethod(arg0: string): Promise<Array<AuthenticationEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuthenticationAuditLogByMethod(arg0);
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuthenticationAuditLogByMethod(arg0);
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAuthenticationAuditLogByPrincipal(arg0: Principal): Promise<Array<AuthenticationEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuthenticationAuditLogByPrincipal(arg0);
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuthenticationAuditLogByPrincipal(arg0);
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAuthenticationAuditLogByStatus(arg0: string): Promise<Array<AuthenticationEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuthenticationAuditLogByStatus(arg0);
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuthenticationAuditLogByStatus(arg0);
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBtcBalance(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getBtcBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBtcBalance(arg0);
            return result;
        }
    }
    async getBtcTransactionHistory(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getBtcTransactionHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBtcTransactionHistory(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDisplayNameChangeHistory(): Promise<Array<DisplayNameChangeHistory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDisplayNameChangeHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDisplayNameChangeHistory();
            return result;
        }
    }
    async getDisplayNameChangeHistoryByDisplayName(arg0: string): Promise<Array<DisplayNameChangeHistory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDisplayNameChangeHistoryByDisplayName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDisplayNameChangeHistoryByDisplayName(arg0);
            return result;
        }
    }
    async getDisplayNameChangeHistoryByPrincipal(arg0: Principal): Promise<Array<DisplayNameChangeHistory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDisplayNameChangeHistoryByPrincipal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDisplayNameChangeHistoryByPrincipal(arg0);
            return result;
        }
    }
    async getEpiqIdByPrincipal(arg0: Principal): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getEpiqIdByPrincipal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEpiqIdByPrincipal(arg0);
            return result;
        }
    }
    async getEthBalance(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getEthBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEthBalance(arg0);
            return result;
        }
    }
    async getEthTransactionHistory(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getEthTransactionHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEthTransactionHistory(arg0);
            return result;
        }
    }
    async getIcpBalance(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getIcpBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIcpBalance(arg0);
            return result;
        }
    }
    async getIcpTransactionHistory(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getIcpTransactionHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIcpTransactionHistory(arg0);
            return result;
        }
    }
    async getMessagesWithUser(arg0: Principal): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessagesWithUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessagesWithUser(arg0);
            return result;
        }
    }
    async getPrincipalByEpiqId(arg0: string): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrincipalByEpiqId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrincipalByEpiqId(arg0);
            return result;
        }
    }
    async getTransaction(arg0: bigint): Promise<Transaction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransaction(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransaction(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserCourseProgress(arg0: Principal): Promise<Array<CourseProgress>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserCourseProgress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserCourseProgress(arg0);
            return result;
        }
    }
    async getUserEpqRewards(arg0: Principal): Promise<Array<EpqReward>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserEpqRewards(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserEpqRewards(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserQuestProgress(arg0: Principal): Promise<Array<QuestProgress>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserQuestProgress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserQuestProgress(arg0);
            return result;
        }
    }
    async getUserQuestProgressRecords(arg0: Principal): Promise<Array<QuestProgressRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserQuestProgressRecords(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserQuestProgressRecords(arg0);
            return result;
        }
    }
    async getUserTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserTransactions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserTransactions();
            return result;
        }
    }
    async getWallet(arg0: bigint): Promise<EpiqWallet> {
        if (this.processError) {
            try {
                const result = await this.actor.getWallet(arg0);
                return from_candid_EpiqWallet_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWallet(arg0);
            return from_candid_EpiqWallet_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasValidFirebaseSession(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasValidFirebaseSession();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasValidFirebaseSession();
            return result;
        }
    }
    async importSingleFirebaseUser(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.importSingleFirebaseUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importSingleFirebaseUser(arg0);
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listWallets(): Promise<Array<EpiqWallet>> {
        if (this.processError) {
            try {
                const result = await this.actor.listWallets();
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listWallets();
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async logoutFirebaseSession(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logoutFirebaseSession();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logoutFirebaseSession();
            return result;
        }
    }
    async lookupPrincipalByEpiqId(arg0: string): Promise<Principal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.lookupPrincipalByEpiqId(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.lookupPrincipalByEpiqId(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async mapEpiqIdToPrincipal(arg0: string, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.mapEpiqIdToPrincipal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.mapEpiqIdToPrincipal(arg0, arg1);
            return result;
        }
    }
    async markMessageAsRead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markMessageAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markMessageAsRead(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async sendMessage(arg0: Principal, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async syncFirebaseUserData(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.syncFirebaseUserData(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.syncFirebaseUserData(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateCourseProgress(arg0: bigint, arg1: Array<bigint>, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCourseProgress(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCourseProgress(arg0, arg1, arg2);
            return result;
        }
    }
    async updateQuestProgress(arg0: bigint, arg1: Array<bigint>, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateQuestProgress(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateQuestProgress(arg0, arg1, arg2);
            return result;
        }
    }
    async updateQuestProgressRecord(arg0: bigint, arg1: Array<bigint>, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateQuestProgressRecord(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateQuestProgressRecord(arg0, arg1, arg2);
            return result;
        }
    }
    async updateUserMemberType(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserMemberType(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserMemberType(arg0, arg1);
            return result;
        }
    }
    async updateWalletLabel(arg0: bigint, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWalletLabel(arg0, to_candid_opt_n24(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWalletLabel(arg0, to_candid_opt_n24(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_AuthenticationEvent_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuthenticationEvent): AuthenticationEvent {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_Chain_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Chain): Chain {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_CourseModuleContent_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CourseModuleContent): CourseModuleContent {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_CourseModuleWithQuestions_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CourseModuleWithQuestions): CourseModuleWithQuestions {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_CourseWithModules_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CourseWithModules): CourseWithModules {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_EpiqWallet_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EpiqWallet): EpiqWallet {
    return from_candid_record_n54(_uploadFile, _downloadFile, value);
}
function from_candid_FirebaseAuthResponse_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FirebaseAuthResponse): FirebaseAuthResponse {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_MemberType_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MemberType): MemberType {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_QuestModule_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestModule): QuestModule {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_QuestStep_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestStep): QuestStep {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_QuizQuestion>]): Array<QuizQuestion> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Transaction]): Transaction | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    epiqId: [] | [string];
    displayName: [] | [string];
    sessionExpiresAt: [] | [_Time];
    walletAddress: [] | [string];
    email: [] | [string];
    message: string;
    memberType: [] | [string];
    success: boolean;
    principalId: [] | [Principal];
}): {
    epiqId?: string;
    displayName?: string;
    sessionExpiresAt?: Time;
    walletAddress?: string;
    email?: string;
    message: string;
    memberType?: string;
    success: boolean;
    principalId?: Principal;
} {
    return {
        epiqId: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.epiqId)),
        displayName: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.displayName)),
        sessionExpiresAt: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.sessionExpiresAt)),
        walletAddress: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.walletAddress)),
        email: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.email)),
        message: value.message,
        memberType: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.memberType)),
        success: value.success,
        principalId: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.principalId))
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    chain: _Chain;
    privateKey: [] | [string];
    address: string;
    recoveryPhrase: [] | [string];
    walletId: bigint;
}): {
    chain: Chain;
    privateKey?: string;
    address: string;
    recoveryPhrase?: string;
    walletId: bigint;
} {
    return {
        chain: from_candid_Chain_n26(_uploadFile, _downloadFile, value.chain),
        privateKey: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.privateKey)),
        address: value.address,
        recoveryPhrase: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.recoveryPhrase)),
        walletId: value.walletId
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    reward: bigint;
    title: string;
    availableToAll: boolean;
    description: string;
    assignedMemberTypes: Array<_MemberType>;
    category: string;
    modules: Array<_CourseModuleWithQuestions>;
}): {
    id: bigint;
    reward: bigint;
    title: string;
    availableToAll: boolean;
    description: string;
    assignedMemberTypes: Array<MemberType>;
    category: string;
    modules: Array<CourseModuleWithQuestions>;
} {
    return {
        id: value.id,
        reward: value.reward,
        title: value.title,
        availableToAll: value.availableToAll,
        description: value.description,
        assignedMemberTypes: from_candid_vec_n31(_uploadFile, _downloadFile, value.assignedMemberTypes),
        category: value.category,
        modules: from_candid_vec_n34(_uploadFile, _downloadFile, value.modules)
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    content: _CourseModuleContent;
    description: string;
    questions: Array<_QuizQuestion>;
}): {
    id: bigint;
    title: string;
    content: CourseModuleContent;
    description: string;
    questions: Array<QuizQuestion>;
} {
    return {
        id: value.id,
        title: value.title,
        content: from_candid_CourseModuleContent_n37(_uploadFile, _downloadFile, value.content),
        description: value.description,
        questions: value.questions
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    doStep: [] | [Array<_QuizQuestion>];
    show: [] | [string];
    tell: string;
}): {
    doStep?: Array<QuizQuestion>;
    show?: string;
    tell: string;
} {
    return {
        doStep: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.doStep)),
        show: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.show)),
        tell: value.tell
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    reward: bigint;
    title: string;
    description: string;
    steps: Array<_QuestStep>;
    category: string;
}): {
    id: bigint;
    reward: bigint;
    title: string;
    description: string;
    steps: Array<QuestStep>;
    category: string;
} {
    return {
        id: value.id,
        reward: value.reward,
        title: value.title,
        description: value.description,
        steps: from_candid_vec_n43(_uploadFile, _downloadFile, value.steps),
        category: value.category
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    content: string;
    stepType: string;
    quizQuestions: [] | [Array<_QuizQuestion>];
    videoUrl: [] | [string];
}): {
    id: bigint;
    title: string;
    content: string;
    stepType: string;
    quizQuestions?: Array<QuizQuestion>;
    videoUrl?: string;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        stepType: value.stepType,
        quizQuestions: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.quizQuestions)),
        videoUrl: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.videoUrl))
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    epiqId: [] | [string];
    failureReason: [] | [string];
    authMethod: string;
    ipContext: [] | [string];
    timestamp: _Time;
    principalId: Principal;
}): {
    status: string;
    epiqId?: string;
    failureReason?: string;
    authMethod: string;
    ipContext?: string;
    timestamp: Time;
    principalId: Principal;
} {
    return {
        status: value.status,
        epiqId: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.epiqId)),
        failureReason: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.failureReason)),
        authMethod: value.authMethod,
        ipContext: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.ipContext)),
        timestamp: value.timestamp,
        principalId: value.principalId
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    publicAddress: string;
    metadata: [] | [string];
    chain: _Chain;
    createdAt: _Time;
    privateKey: [] | [string];
    recoveryPhrase: [] | [string];
    walletLabel: [] | [string];
    walletId: bigint;
}): {
    publicAddress: string;
    metadata?: string;
    chain: Chain;
    createdAt: Time;
    privateKey?: string;
    recoveryPhrase?: string;
    walletLabel?: string;
    walletId: bigint;
} {
    return {
        publicAddress: value.publicAddress,
        metadata: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.metadata)),
        chain: from_candid_Chain_n26(_uploadFile, _downloadFile, value.chain),
        createdAt: value.createdAt,
        privateKey: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.privateKey)),
        recoveryPhrase: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.recoveryPhrase)),
        walletLabel: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.walletLabel)),
        walletId: value.walletId
    };
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    btc: null;
} | {
    evm: null;
} | {
    icp: null;
} | {
    custom: null;
}): Chain {
    return "btc" in value ? Chain.btc : "evm" in value ? Chain.evm : "icp" in value ? Chain.icp : "custom" in value ? Chain.custom : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    member: null;
} | {
    trustee: null;
} | {
    admin: null;
} | {
    citizen: null;
} | {
    beneficiary: null;
} | {
    superAdmin: null;
} | {
    business: null;
} | {
    ambassador: null;
} | {
    partner: null;
}): MemberType {
    return "member" in value ? MemberType.member : "trustee" in value ? MemberType.trustee : "admin" in value ? MemberType.admin : "citizen" in value ? MemberType.citizen : "beneficiary" in value ? MemberType.beneficiary : "superAdmin" in value ? MemberType.superAdmin : "business" in value ? MemberType.business : "ambassador" in value ? MemberType.ambassador : "partner" in value ? MemberType.partner : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CourseWithModules>): Array<CourseWithModules> {
    return value.map((x)=>from_candid_CourseWithModules_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MemberType>): Array<MemberType> {
    return value.map((x)=>from_candid_MemberType_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CourseModuleWithQuestions>): Array<CourseModuleWithQuestions> {
    return value.map((x)=>from_candid_CourseModuleWithQuestions_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QuestModule>): Array<QuestModule> {
    return value.map((x)=>from_candid_QuestModule_n41(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QuestStep>): Array<QuestStep> {
    return value.map((x)=>from_candid_QuestStep_n44(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AuthenticationEvent>): Array<AuthenticationEvent> {
    return value.map((x)=>from_candid_AuthenticationEvent_n47(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EpiqWallet>): Array<EpiqWallet> {
    return value.map((x)=>from_candid_EpiqWallet_n53(_uploadFile, _downloadFile, x));
}
function to_candid_CourseModuleContent_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CourseModuleContent): _CourseModuleContent {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_CourseModuleWithQuestions_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CourseModuleWithQuestions): _CourseModuleWithQuestions {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_MemberType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MemberType): _MemberType {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<CourseModuleWithQuestions> | null): [] | [Array<_CourseModuleWithQuestions>] {
    return value === null ? candid_none() : candid_some(to_candid_vec_n16(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    content: CourseModuleContent;
    description: string;
    questions: Array<QuizQuestion>;
}): {
    id: bigint;
    title: string;
    content: _CourseModuleContent;
    description: string;
    questions: Array<_QuizQuestion>;
} {
    return {
        id: value.id,
        title: value.title,
        content: to_candid_CourseModuleContent_n19(_uploadFile, _downloadFile, value.content),
        description: value.description,
        questions: value.questions
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    doStep?: Array<QuizQuestion>;
    show?: string;
    tell: string;
}): {
    doStep: [] | [Array<_QuizQuestion>];
    show: [] | [string];
    tell: string;
} {
    return {
        doStep: value.doStep ? candid_some(value.doStep) : candid_none(),
        show: value.show ? candid_some(value.show) : candid_none(),
        tell: value.tell
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MemberType): {
    member: null;
} | {
    trustee: null;
} | {
    admin: null;
} | {
    citizen: null;
} | {
    beneficiary: null;
} | {
    superAdmin: null;
} | {
    business: null;
} | {
    ambassador: null;
} | {
    partner: null;
} {
    return value == MemberType.member ? {
        member: null
    } : value == MemberType.trustee ? {
        trustee: null
    } : value == MemberType.admin ? {
        admin: null
    } : value == MemberType.citizen ? {
        citizen: null
    } : value == MemberType.beneficiary ? {
        beneficiary: null
    } : value == MemberType.superAdmin ? {
        superAdmin: null
    } : value == MemberType.business ? {
        business: null
    } : value == MemberType.ambassador ? {
        ambassador: null
    } : value == MemberType.partner ? {
        partner: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<CourseModuleWithQuestions>): Array<_CourseModuleWithQuestions> {
    return value.map((x)=>to_candid_CourseModuleWithQuestions_n17(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<MemberType>): Array<_MemberType> {
    return value.map((x)=>to_candid_MemberType_n22(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
